# Базовый образ PostgreSQL
FROM postgres:15

# Устанавливаем переменные окружения
ENV POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=admin \
    POSTGRES_DB=postgres

# Копируем SQL-файл внутрь образа
# Все скрипты в этой папке выполняются при первом запуске контейнера
COPY init.sql /docker-entrypoint-initdb.d/