package domain

import "errors"

var (
	ErrNotFound              = errors.New("not found")
	ErrInvalidInput          = errors.New("invalid input")
	ErrNoFieldsToUpdate      = errors.New("no fields to update")
	ErrAttendanceNotFound    = errors.New("attendance not found")
	ErrProjectIDRequired     = errors.New("project_id is required")
	ErrCreatedByRequired     = errors.New("created_by is required")
	ErrInvalidProjectID      = errors.New("invalid project id")
	ErrInvalidProjectIDAlt   = errors.New("invalid project_id")
	ErrBoardNotFound         = errors.New("board not found")
	ErrInvalidBoardID        = errors.New("invalid board id")
	ErrReportNotFound        = errors.New("report not found")
	ErrHelpRequestNotFound   = errors.New("help request not found")
	ErrCompletedWorkNotFound = errors.New("completed work not found")
	ErrTomorrowPlanNotFound  = errors.New("tomorrow plans not found")
	ErrForumMessageNotFound  = errors.New("forum message not found")
	ErrProblemNotFound       = errors.New("problem not found")
	ErrProjectNotFound       = errors.New("project not found")
	ErrRoleNotFound          = errors.New("role not found")
	ErrStatusNotFound        = errors.New("status not found")
	ErrSubscriptionNotFound  = errors.New("subscription not found")
	ErrTaskNotFound          = errors.New("task not found")
	ErrUserNotFound          = errors.New("user not found")
	ErrTeamNotFound          = errors.New("team not found")
	ErrTeamMemberNotFound    = errors.New("team member not found")
	ErrProjectTeamNotFound   = errors.New("project team not found")
	ErrUserRoleNotFound      = errors.New("user role not found")
	ErrAssigneeNotFound      = errors.New("assignee not found")
	ErrCreatorNotFound       = errors.New("creator not found")
	ErrInvalidUserID         = errors.New("invalid user id")
	ErrInvalidUserIDAlt      = errors.New("invalid user_id")
	ErrInvalidSubscriptionID = errors.New("invalid subscription id")
	ErrInvalidAssignedTo     = errors.New("invalid assigned_to")
	ErrInvalidCreatorID      = errors.New("invalid creator id")
	ErrInvalidCreatorIDAlt   = errors.New("invalid creator_id")
	ErrInvalidStatusID       = errors.New("invalid status_id")
	ErrInvalidProblemID      = errors.New("invalid problem id")
	ErrInvalidTypeObject     = errors.New("invalid type object")
	ErrDifferentBoard        = errors.New("different board")
	ErrNotAllUsersFound      = errors.New("not all users founded")
)
